name: deception_app
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text_field: ^1.0.0-nullsafety.1
  bloc: ^7.0.0-nullsafety.3
  build_context: ^2.0.4
  email_validator: ^2.0.0-nullsafety 
  flutter_bloc: ^7.0.0-nullsafety.3
  google_fonts: ^2.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0-nullsafety.1
  mocktail: 0.0.1-dev.12
  very_good_analysis: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
