name: deception_app

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed lib test

      # - name: Analyze
      #   run: flutter analyze lib test

      # - name: Run tests
      #   run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

      # - name: Check Code Coverage
      #   uses: VeryGoodOpenSource/very_good_coverage@v1.1.1

      - name: build
        run: flutter build web -t ./lib/main_production.dart

      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DECEPTION_PROD }}'
          channelId: live
          projectId: deception-prod
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

